### ISSUE TITLE
Code Climate badge doesn't link to Codeclimate Overview for repo

### ISSUE THREAD

**Issue by CodyBrewer** [Lambda-School-Labs/nutrivurv-be#46]
The Codeclimate badges just link to the images of themselves. We need to have them set up so they link to code climate properly.

**Comment by CodyBrewer** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Code Climate badge doesn't link to Codeclimate Overview for repo](https://trello.com/c/43tAu7tK/47-code-climate-badge-doesnt-link-to-codeclimate-overview-for-repo)

**Comment by dave-vazquez** [comment]
Fix requires access to repo settings. #50 is open for review.

**Comment by CodyBrewer** [comment]
Fixed with #50 thank you @dave-vazquez!
