### ISSUE TITLE
getUserId.js isLoggedIn has a Cognitive Complexity of 25 (exceeds 5 allowed) and has 43 Lines of Code (exceeds 25 allowed)

### ISSUE THREAD

**Issue by CodyBrewer** [Lambda-School-Labs/nutrivurv-be#47]
[Code Climate Link](https://codeclimate.com/github/Lambda-School-Labs/nutrition-tracker-be-pt7/issues?category=complexity&engine_name%5B%5D=structure&engine_name%5B%5D=duplication)

Code Climate estimated time to fix: 3hours 

@Afrodo1 and I have brought discussed not really understanding what this code means with the use of the ctx parameter within this function.

This could be fixed with the resolution of Issue #43 as we are rehauling authentication

**Comment by CodyBrewer** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Codeclimate Score of D with 23 Issues](https://trello.com/c/36uMpJRK/46-codeclimate-score-of-d-with-23-issues)

**Comment by CodyBrewer** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Refactor utils/](https://trello.com/c/rLoLScuR/70-refactor-utils)

**Comment by dave-vazquez** [comment]
Lambda's Code Climate docs have been updated to include a switch in the `codeclimate.yml` file to turn off similar code checks. Reasoning is that they lead to too many false positive which seems to be the case for most if not all of these duplication issues.

They've also including an option to increase the threshold for # of lines to 50 which is more reasonable for Javascript.

This may not remove all of the duplication or line threshold issues, but should remove most of the erroneous ones. Let's see how the maintainability report changes after adding these changes.

- [Labs Code Climate Docs](https://www.notion.so/Code-Climate-96121e3146654095ac2ca9155d79bdda)
- [Code Climate - Advanced Configuration](https://docs.codeclimate.com/docs/advanced-configuration#section-exclude-patterns)

PR #54 is open for review

**Comment by dave-vazquez** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Update Code Climate Configuration to ignore false positives for similar code checks, and update the line # threshold for methods/functions](https://trello.com/c/tL7OVNUb/80-update-code-climate-configuration-to-ignore-false-positives-for-similar-code-checks-and-update-the-line-threshold-for-methods-fu)

**Comment by dave-vazquez** [comment]
Line threshold issue has been removed from maintainability report.
